# Generated by Django 3.0 on 2019-12-09 14:21

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('billing_sessions', '0003_auto_20191209_1421'),
    ]

    operations = [
        migrations.CreateModel(
            name='Calendar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateField(default=django.utils.timezone.now)),
                ('end', models.DateField(null=True, unique=True)),
                ('absentees', models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(2147483647)])),
                ('amount', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calendars', to='billing_sessions.BillingSession')),
            ],
            options={
                'ordering': ['start'],
            },
        ),
    ]
