# Generated by Django 3.0 on 2019-12-06 15:11

import accounts.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('username', models.CharField(help_text='please use only numbers and alphabets', max_length=20, primary_key=True, serialize=False, validators=[accounts.validators.validate_username], verbose_name='Username')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(help_text='use at least 8 characters', max_length=300)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_superuser', models.BooleanField(default=False)),
                ('current_session_id', models.IntegerField(null=True, unique=True)),
            ],
            options={
                'verbose_name': 'user',
                'ordering': ['username'],
            },
        ),
    ]
