# Generated by Django 3.0 on 2019-12-05 06:47

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BillingSession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateField(default=django.utils.timezone.now, unique=True)),
                ('end', models.DateField(null=True, unique=True)),
                ('absentees', models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(2147483647)])),
                ('amount', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='accounts.CustomUser')),
            ],
            options={
                'ordering': ['start'],
            },
        ),
    ]
