# Generated by Django 3.0 on 2019-12-07 13:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('billing_sessions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billingsession',
            name='start',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
