# Generated by Django 3.0 on 2019-12-24 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing_sessions", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="billingsession",
            name="prev_session",
            field=models.IntegerField(null=True, unique=True),
        ),
    ]
