# Generated by Django 3.0 on 2019-12-24 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing_sessions", "0002_billingsession_prev_session"),
    ]

    operations = [
        migrations.AlterField(
            model_name="billingsession",
            name="end",
            field=models.DateField(blank=True, null=True),
        ),
    ]
