# Generated by Django 3.0 on 2019-12-09 14:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing_sessions', '0002_auto_20191207_1300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billingsession',
            name='absentees',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(31)]),
        ),
    ]
